language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

after_success:
  - go build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: lambda
    function_name: "lambda-test"
    region: "	eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "nodejs8.10"
    handler_name: "handler"

