# Use an official Python runtime as a parent image
FROM alpine

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["smart2"]
